# Generated by Django 6.0 on 2025-12-25 12:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Student Name')),
                ('father_name', models.CharField(max_length=255, verbose_name='Father/Guardian Name')),
                ('cnic', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="CNIC must be in the format: 'XXXXX-XXXXXXX-X'.", regex='^\\d{5}-\\d{7}-\\d{1}$')], verbose_name='CNIC / B-Form')),
                ('mobile_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+92-3XX-XXXXXXX'.", regex='^\\+92-\\d{3}-\\d{7}$')], verbose_name='Mobile Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('admission_date', models.DateField(auto_now_add=True, verbose_name='Date of Admission')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Left', 'Left')], default='Active', max_length=10, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Enrollment')),
                ('enrolled_class', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to='administration.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'ordering': ['-start_date'],
            },
        ),
    ]
