# Generated by Django 5.0.1 on 2025-12-28 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='progress',
            field=models.CharField(blank=True, max_length=255, verbose_name='Progress/Subject'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Transferred', 'Transferred'), ('Left', 'Left'), ('Expelled', 'Expelled')], default='Active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10-15 digits. Example: +92-300-1234567 or 03001234567', regex='^[\\+]?[\\d\\-\\s]{10,15}$')], verbose_name='Mobile Number'),
        ),
    ]
